library(readxl)
library(dplyr)
library(stringr)
xlsdata <- read_excel("D:/kwh/Rproject data/2/전국주차장정보표준데이터-20220419.xls")
apple <- xlsdata%>%filter(제공기관명=="경기도 수원시")
banana <- apple%>%select(주차장명,주차장구분,소재지지번주소) 
banana$소재지지번주소<- gsub(" ","",banana$소재지지번주소)
banana$소재지지번주소<- substr(banana$소재지지번주소,7,9)
View(banana)
